apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ihsm-net
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: ihsm-net
spec:
  source:
    git:
      url: https://github.com/richardb-ihsm/tap-test
      ref:
        branch: main
